spring:
  main:
    banner-mode: off

  datasource:
    url: "jdbc:h2:mem:testdb"
    username: sa
    password: password
    driverClassName: org.h2.Driver

  database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    url: ${datasource.url}
#    username: ${datasource.username}
#    password: ${datasource.password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

app:
  description: ${app.description}
  version: ${app.version}
  server:
    url: ${app.server.url}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  name: heal
  description: ${app.description}

springdoc:
  api-docs:
    path: /api-docs